// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: java.capnp

#ifndef CAPNP_INCLUDED_c5f1af96651f70ea_
#define CAPNP_INCLUDED_c5f1af96651f70ea_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 5003
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(9ee4c8f803b3b596);
CAPNP_DECLARE_SCHEMA(9b066bb4881f7cd3);

}  // namespace schemas
}  // namespace capnp


// =======================================================================================

// =======================================================================================


#endif  // CAPNP_INCLUDED_c5f1af96651f70ea_
